site_name: TencentOS
theme:
  name: 'material'
  language: zh
  features:
    - navigation.tabs
    - navigation.sections

nav:
  - 首页: guide/config.md
  - 快速入门:
    - 下载及安装: guide/config.md
    - 使用说明: guide/config.md
  - 用户指南:
    - 基础配置: guide/stroge.md
    - 系统管理: guide/config.md
    - 内核更新: guide/config.md
    - 系统状态监控: guide/monitor.md
    - 安全加固: guide/config.md
    - 网络管理: guide/config.md
    - 存储管理: guide/config.md
    - 兼容硬件: guide/config.md
  - 版本说明:
    - v8.5: guide/config.md
    - v8.6: guide/config.md
    - OpenCloudOS Stream: guide/config.md
    - OpenCloudOS Stream Kernel: guide/config.md
  - 常见问题: guide/config.md
  - 如何贡献: guide/config.md